{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kube-headscale.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "kube-headscale.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-headscale.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
