apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-headscale.fullname" . }}
  labels:
    {{- include "kube-headscale.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.https.port | default (include "kube-headscale.defaultPort" .) }}
      targetPort: {{ include "kube-headscale.portName" . }}
      protocol: TCP
      name: {{ include "kube-headscale.portName" . }}
    - port: {{ .Values.service.stun.port }}
      targetPort: stun
      protocol: TCP
      name: stun
    - port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "kube-headscale.selectorLabels" . | nindent 4 }}
